export default {
  C: {
    type: 'programming',
    color: '#555555',
    extensions: ['.c', '.cats', '.h', '.idc'],
    interpreters: ['tcc'],
    ace_mode: 'c_cpp',
    codemirror_mode: 'clike',
    codemirror_mime_type: 'text/x-csrc',
    language_id: 41
  },
  'C#': {
    type: 'programming',
    ace_mode: 'csharp',
    codemirror_mode: 'clike',
    codemirror_mime_type: 'text/x-csharp',
    tm_scope: 'source.cs',
    color: '#178600',
    aliases: ['csharp'],
    extensions: ['.cs', '.cake', '.cshtml', '.csx'],
    language_id: 42
  },
  'C++': {
    type: 'programming',
    ace_mode: 'c_cpp',
    codemirror_mode: 'clike',
    codemirror_mime_type: 'text/x-c++src',
    color: '#f34b7d',
    aliases: ['cpp'],
    extensions: [
      '.cpp',
      '.c++',
      '.cc',
      '.cp',
      '.cxx',
      '.h',
      '.h++',
      '.hh',
      '.hpp',
      '.hxx',
      '.inc',
      '.inl',
      '.ino',
      '.ipp',
      '.re',
      '.tcc',
      '.tpp'
    ],
    language_id: 43
  },
  CSS: {
    type: 'markup',
    tm_scope: 'source.css',
    ace_mode: 'css',
    codemirror_mode: 'css',
    codemirror_mime_type: 'text/css',
    color: '#563d7c',
    extensions: ['.css'],
    language_id: 50
  },
  Clojure: {
    type: 'programming',
    ace_mode: 'clojure',
    codemirror_mode: 'clojure',
    codemirror_mime_type: 'text/x-clojure',
    color: '#db5855',
    extensions: ['.clj', '.boot', '.cl2', '.cljc', '.cljs', '.cljs.hl', '.cljscm', '.cljx', '.hic'],
    filenames: ['riemann.config'],
    language_id: 62
  },
  CoffeeScript: {
    type: 'programming',
    tm_scope: 'source.coffee',
    ace_mode: 'coffee',
    codemirror_mode: 'coffeescript',
    codemirror_mime_type: 'text/x-coffeescript',
    color: '#244776',
    aliases: ['coffee', 'coffee-script'],
    extensions: ['.coffee', '._coffee', '.cake', '.cjsx', '.iced'],
    filenames: ['Cakefile'],
    interpreters: ['coffee'],
    language_id: 63
  },
  'Common Lisp': {
    type: 'programming',
    tm_scope: 'source.lisp',
    color: '#3fb68b',
    aliases: ['lisp'],
    extensions: ['.lisp', '.asd', '.cl', '.l', '.lsp', '.ny', '.podsl', '.sexp'],
    interpreters: ['lisp', 'sbcl', 'ccl', 'clisp', 'ecl'],
    ace_mode: 'lisp',
    codemirror_mode: 'commonlisp',
    codemirror_mime_type: 'text/x-common-lisp',
    language_id: 66
  },
  'Component Pascal': {
    type: 'programming',
    color: '#B0CE4E',
    extensions: ['.cp', '.cps'],
    tm_scope: 'source.pascal',
    aliases: ['delphi', 'objectpascal'],
    ace_mode: 'pascal',
    codemirror_mode: 'pascal',
    codemirror_mime_type: 'text/x-pascal',
    language_id: 67
  },
  Crystal: {
    type: 'programming',
    color: '#000100',
    extensions: ['.cr'],
    ace_mode: 'ruby',
    codemirror_mode: 'crystal',
    codemirror_mime_type: 'text/x-crystal',
    tm_scope: 'source.crystal',
    interpreters: ['crystal'],
    language_id: 72
  },
  Dart: {
    type: 'programming',
    color: '#00B4AB',
    extensions: ['.dart'],
    interpreters: ['dart'],
    ace_mode: 'dart',
    codemirror_mode: 'dart',
    codemirror_mime_type: 'application/dart',
    language_id: 87
  },
  Dockerfile: {
    type: 'programming',
    color: '#0db7ed',
    tm_scope: 'source.dockerfile',
    extensions: ['.dockerfile'],
    filenames: ['Dockerfile'],
    ace_mode: 'dockerfile',
    codemirror_mode: 'dockerfile',
    codemirror_mime_type: 'text/x-dockerfile',
    language_id: 89
  },
  Elixir: {
    type: 'programming',
    color: '#6e4a7e',
    extensions: ['.ex', '.exs'],
    ace_mode: 'elixir',
    filenames: ['mix.lock'],
    interpreters: ['elixir'],
    language_id: 100
  },
  EmberScript: {
    type: 'programming',
    color: '#FFF4F3',
    extensions: ['.em', '.emberscript'],
    tm_scope: 'source.coffee',
    ace_mode: 'coffee',
    codemirror_mode: 'coffeescript',
    codemirror_mime_type: 'text/x-coffeescript',
    language_id: 103
  },
  Erlang: {
    type: 'programming',
    color: '#B83998',
    extensions: ['.erl', '.app.src', '.es', '.escript', '.hrl', '.xrl', '.yrl'],
    filenames: ['Emakefile', 'rebar.config', 'rebar.config.lock', 'rebar.lock'],
    ace_mode: 'erlang',
    codemirror_mode: 'erlang',
    codemirror_mime_type: 'text/x-erlang',
    interpreters: ['escript'],
    language_id: 104
  },
  Go: {
    type: 'programming',
    color: '#375eab',
    aliases: ['golang'],
    extensions: ['.go'],
    ace_mode: 'golang',
    codemirror_mode: 'go',
    codemirror_mime_type: 'text/x-go',
    language_id: 132
  },
  GraphQL: {
    type: 'data',
    extensions: ['.graphql', '.gql'],
    tm_scope: 'source.graphql',
    ace_mode: 'text',
    language_id: 139
  },
  Groovy: {
    type: 'programming',
    ace_mode: 'groovy',
    codemirror_mode: 'groovy',
    codemirror_mime_type: 'text/x-groovy',
    color: '#e69f56',
    extensions: ['.groovy', '.grt', '.gtpl', '.gvy'],
    interpreters: ['groovy'],
    filenames: ['Jenkinsfile'],
    language_id: 142
  },
  HCL: {
    type: 'programming',
    extensions: ['.hcl', '.tf', '.tfvars', '.workflow'],
    ace_mode: 'ruby',
    codemirror_mode: 'ruby',
    codemirror_mime_type: 'text/x-ruby',
    tm_scope: 'source.terraform',
    language_id: 144
  },
  HTML: {
    type: 'markup',
    tm_scope: 'text.html.basic',
    ace_mode: 'html',
    codemirror_mode: 'htmlmixed',
    codemirror_mime_type: 'text/html',
    color: '#e34c26',
    aliases: ['xhtml'],
    extensions: ['.html', '.htm', '.html.hl', '.inc', '.st', '.xht', '.xhtml'],
    language_id: 146
  },
  Haskell: {
    type: 'programming',
    color: '#5e5086',
    extensions: ['.hs', '.hsc'],
    interpreters: ['runhaskell'],
    ace_mode: 'haskell',
    codemirror_mode: 'haskell',
    codemirror_mime_type: 'text/x-haskell',
    language_id: 157
  },
  JSON: {
    type: 'data',
    tm_scope: 'source.json',
    group: 'JavaScript',
    ace_mode: 'json',
    codemirror_mode: 'javascript',
    codemirror_mime_type: 'application/json',
    searchable: false,
    extensions: [
      '.json',
      '.avsc',
      '.geojson',
      '.gltf',
      '.JSON-tmLanguage',
      '.jsonl',
      '.tfstate',
      '.tfstate.backup',
      '.topojson',
      '.webapp',
      '.webmanifest',
      '.yy',
      '.yyp'
    ],
    filenames: [
      '.arcconfig',
      '.htmlhintrc',
      '.tern-config',
      '.tern-project',
      'composer.lock',
      'mcmod.info'
    ],
    language_id: 174
  },
  JSX: {
    type: 'programming',
    group: 'JavaScript',
    extensions: ['.jsx'],
    tm_scope: 'source.js.jsx',
    ace_mode: 'javascript',
    codemirror_mode: 'jsx',
    codemirror_mime_type: 'text/jsx',
    language_id: 178
  },
  Java: {
    type: 'programming',
    ace_mode: 'java',
    codemirror_mode: 'clike',
    codemirror_mime_type: 'text/x-java',
    color: '#b07219',
    extensions: ['.java'],
    language_id: 181
  },
  JavaScript: {
    type: 'programming',
    tm_scope: 'source.js',
    ace_mode: 'javascript',
    codemirror_mode: 'javascript',
    codemirror_mime_type: 'text/javascript',
    color: '#f1e05a',
    aliases: ['js', 'node'],
    extensions: [
      '.js',
      '._js',
      '.bones',
      '.es',
      '.es6',
      '.frag',
      '.gs',
      '.jake',
      '.jsb',
      '.jscad',
      '.jsfl',
      '.jsm',
      '.jss',
      '.mjs',
      '.njs',
      '.pac',
      '.sjs',
      '.ssjs',
      '.xsjs',
      '.xsjslib'
    ],
    filenames: ['Jakefile'],
    interpreters: ['node'],
    language_id: 183
  },
  Kotlin: {
    type: 'programming',
    color: '#F18E33',
    extensions: ['.kt', '.ktm', '.kts'],
    tm_scope: 'source.kotlin',
    ace_mode: 'text',
    codemirror_mode: 'clike',
    codemirror_mime_type: 'text/x-kotlin',
    language_id: 189
  },
  Less: {
    type: 'markup',
    group: 'CSS',
    extensions: ['.less'],
    tm_scope: 'source.css.less',
    ace_mode: 'less',
    codemirror_mode: 'css',
    codemirror_mime_type: 'text/css',
    language_id: 198
  },
  Lua: {
    type: 'programming',
    ace_mode: 'lua',
    codemirror_mode: 'lua',
    codemirror_mime_type: 'text/x-lua',
    color: '#000080',
    extensions: ['.lua', '.fcgi', '.nse', '.p8', '.pd_lua', '.rbxs', '.wlua'],
    interpreters: ['lua'],
    language_id: 213
  },
  OCaml: {
    type: 'programming',
    ace_mode: 'ocaml',
    codemirror_mode: 'mllike',
    codemirror_mime_type: 'text/x-ocaml',
    color: '#3be133',
    extensions: ['.ml', '.eliom', '.eliomi', '.ml4', '.mli', '.mll', '.mly'],
    interpreters: ['ocaml', 'ocamlrun', 'ocamlscript'],
    tm_scope: 'source.ocaml',
    language_id: 255
  },
  'Objective-C': {
    type: 'programming',
    tm_scope: 'source.objc',
    color: '#438eff',
    aliases: ['obj-c', 'objc', 'objectivec'],
    extensions: ['.m', '.h'],
    ace_mode: 'objectivec',
    codemirror_mode: 'clike',
    codemirror_mime_type: 'text/x-objectivec',
    language_id: 257
  },
  PHP: {
    type: 'programming',
    tm_scope: 'text.html.php',
    ace_mode: 'php',
    codemirror_mode: 'php',
    codemirror_mime_type: 'application/x-httpd-php',
    color: '#4F5D95',
    extensions: [
      '.php',
      '.aw',
      '.ctp',
      '.fcgi',
      '.inc',
      '.php3',
      '.php4',
      '.php5',
      '.phps',
      '.phpt'
    ],
    filenames: ['.php', '.php_cs', '.php_cs.dist', 'Phakefile'],
    interpreters: ['php'],
    aliases: ['inc'],
    language_id: 272
  },
  Pascal: {
    type: 'programming',
    color: '#E3F171',
    extensions: ['.pas', '.dfm', '.dpr', '.inc', '.lpr', '.pascal', '.pp'],
    interpreters: ['instantfpc'],
    ace_mode: 'pascal',
    codemirror_mode: 'pascal',
    codemirror_mime_type: 'text/x-pascal',
    language_id: 281
  },
  Perl: {
    type: 'programming',
    tm_scope: 'source.perl',
    ace_mode: 'perl',
    codemirror_mode: 'perl',
    codemirror_mime_type: 'text/x-perl',
    color: '#0298c3',
    extensions: ['.pl', '.al', '.cgi', '.fcgi', '.perl', '.ph', '.plx', '.pm', '.psgi', '.t'],
    filenames: ['Makefile.PL', 'Rexfile', 'ack', 'cpanfile'],
    interpreters: ['cperl', 'perl'],
    aliases: ['cperl'],
    language_id: 282
  },
  'Perl 6': {
    type: 'programming',
    color: '#0000fb',
    extensions: ['.6pl', '.6pm', '.nqp', '.p6', '.p6l', '.p6m', '.pl', '.pl6', '.pm', '.pm6', '.t'],
    interpreters: ['perl6'],
    aliases: ['perl6'],
    tm_scope: 'source.perl6fe',
    ace_mode: 'perl',
    codemirror_mode: 'perl',
    codemirror_mime_type: 'text/x-perl',
    language_id: 283
  },
  Python: {
    type: 'programming',
    ace_mode: 'python',
    codemirror_mode: 'python',
    codemirror_mime_type: 'text/x-python',
    color: '#3572A5',
    extensions: [
      '.py',
      '.bzl',
      '.cgi',
      '.fcgi',
      '.gyp',
      '.gypi',
      '.lmi',
      '.py3',
      '.pyde',
      '.pyi',
      '.pyp',
      '.pyt',
      '.pyw',
      '.rpy',
      '.spec',
      '.tac',
      '.wsgi',
      '.xpy'
    ],
    filenames: [
      '.gclient',
      'BUCK',
      'BUILD',
      'BUILD.bazel',
      'SConscript',
      'SConstruct',
      'Snakefile',
      'WORKSPACE',
      'wscript'
    ],
    interpreters: ['python', 'python2', 'python3'],
    aliases: ['rusthon', 'python3'],
    language_id: 303
  },
  R: {
    type: 'programming',
    color: '#198CE7',
    aliases: ['R', 'Rscript', 'splus'],
    extensions: ['.r', '.rd', '.rsx'],
    filenames: ['.Rprofile', 'expr-dist'],
    interpreters: ['Rscript'],
    ace_mode: 'r',
    codemirror_mode: 'r',
    codemirror_mime_type: 'text/x-rsrc',
    language_id: 307
  },
  REXX: {
    type: 'programming',
    aliases: ['arexx'],
    extensions: ['.rexx', '.pprx', '.rex'],
    interpreters: ['regina', 'rexx'],
    tm_scope: 'source.rexx',
    ace_mode: 'text',
    language_id: 311
  },
  Reason: {
    type: 'programming',
    group: 'OCaml',
    ace_mode: 'rust',
    codemirror_mode: 'rust',
    codemirror_mime_type: 'text/x-rustsrc',
    extensions: ['.re', '.rei'],
    interpreters: ['ocaml'],
    tm_scope: 'source.reason',
    language_id: 869538413
  },
  "Ren'Py": {
    type: 'programming',
    aliases: ['renpy'],
    color: '#ff7f7f',
    extensions: ['.rpy'],
    tm_scope: 'source.renpy',
    ace_mode: 'python',
    language_id: 322
  },
  Ruby: {
    type: 'programming',
    ace_mode: 'ruby',
    codemirror_mode: 'ruby',
    codemirror_mime_type: 'text/x-ruby',
    color: '#701516',
    aliases: ['jruby', 'macruby', 'rake', 'rb', 'rbx'],
    extensions: [
      '.rb',
      '.builder',
      '.eye',
      '.fcgi',
      '.gemspec',
      '.god',
      '.jbuilder',
      '.mspec',
      '.pluginspec',
      '.podspec',
      '.rabl',
      '.rake',
      '.rbuild',
      '.rbw',
      '.rbx',
      '.ru',
      '.ruby',
      '.spec',
      '.thor',
      '.watchr'
    ],
    interpreters: ['ruby', 'macruby', 'rake', 'jruby', 'rbx'],
    filenames: [
      '.irbrc',
      '.pryrc',
      'Appraisals',
      'Berksfile',
      'Brewfile',
      'Buildfile',
      'Capfile',
      'Dangerfile',
      'Deliverfile',
      'Fastfile',
      'Gemfile',
      'Gemfile.lock',
      'Guardfile',
      'Jarfile',
      'Mavenfile',
      'Podfile',
      'Puppetfile',
      'Rakefile',
      'Snapfile',
      'Thorfile',
      'Vagrantfile',
      'buildfile'
    ],
    language_id: 326
  },
  Rust: {
    type: 'programming',
    color: '#dea584',
    extensions: ['.rs', '.rs.in'],
    ace_mode: 'rust',
    codemirror_mode: 'rust',
    codemirror_mime_type: 'text/x-rustsrc',
    language_id: 327
  },
  SCSS: {
    type: 'markup',
    tm_scope: 'source.scss',
    group: 'CSS',
    ace_mode: 'scss',
    codemirror_mode: 'css',
    codemirror_mime_type: 'text/x-scss',
    extensions: ['.scss'],
    language_id: 329
  },
  SQL: {
    type: 'data',
    tm_scope: 'source.sql',
    ace_mode: 'sql',
    codemirror_mode: 'sql',
    codemirror_mime_type: 'text/x-sql',
    extensions: ['.sql', '.cql', '.ddl', '.inc', '.mysql', '.prc', '.tab', '.udf', '.viw'],
    language_id: 333
  },
  STON: {
    type: 'data',
    group: 'Smalltalk',
    extensions: ['.ston'],
    tm_scope: 'source.smalltalk',
    ace_mode: 'text',
    language_id: 336
  },
  Sass: {
    type: 'markup',
    tm_scope: 'source.sass',
    group: 'CSS',
    extensions: ['.sass'],
    ace_mode: 'sass',
    codemirror_mode: 'sass',
    codemirror_mime_type: 'text/x-sass',
    language_id: 340
  },
  Scala: {
    type: 'programming',
    ace_mode: 'scala',
    codemirror_mode: 'clike',
    codemirror_mime_type: 'text/x-scala',
    color: '#c22d40',
    extensions: ['.scala', '.kojo', '.sbt', '.sc'],
    interpreters: ['scala'],
    language_id: 341
  },
  Scheme: {
    type: 'programming',
    color: '#1e4aec',
    extensions: ['.scm', '.sch', '.sld', '.sls', '.sps', '.ss'],
    interpreters: ['guile', 'bigloo', 'chicken', 'csi', 'gosh', 'r6rs'],
    ace_mode: 'scheme',
    codemirror_mode: 'scheme',
    codemirror_mime_type: 'text/x-scheme',
    language_id: 343
  },
  Text: {
    type: 'prose',
    wrap: true,
    aliases: ['fundamental'],
    extensions: ['.txt', '.fr', '.nb', '.ncl', '.no'],
    filenames: [
      'COPYING',
      'COPYING.regex',
      'COPYRIGHT.regex',
      'FONTLOG',
      'INSTALL',
      'INSTALL.mysql',
      'LICENSE',
      'LICENSE.mysql',
      'NEWS',
      'README.1ST',
      'README.me',
      'README.mysql',
      'click.me',
      'delete.me',
      'keep.me',
      'read.me',
      'readme.1st',
      'test.me'
    ],
    tm_scope: 'none',
    ace_mode: 'text',
    language_id: 372
  },
  TypeScript: {
    type: 'programming',
    color: '#2b7489',
    aliases: ['ts'],
    interpreters: ['node'],
    extensions: ['.ts', '.tsx'],
    tm_scope: 'source.ts',
    ace_mode: 'typescript',
    codemirror_mode: 'javascript',
    codemirror_mime_type: 'application/typescript',
    language_id: 378
  },
  Vue: {
    type: 'markup',
    color: '#2c3e50',
    extensions: ['.vue'],
    tm_scope: 'text.html.vue',
    ace_mode: 'html',
    language_id: 391
  },
  WebAssembly: {
    type: 'programming',
    color: '#04133b',
    extensions: ['.wast', '.wat'],
    aliases: ['wast', 'wasm'],
    tm_scope: 'source.webassembly',
    ace_mode: 'lisp',
    codemirror_mode: 'commonlisp',
    codemirror_mime_type: 'text/x-common-lisp',
    language_id: 956556503
  },
  XML: {
    type: 'data',
    ace_mode: 'xml',
    codemirror_mode: 'xml',
    codemirror_mime_type: 'text/xml',
    aliases: ['rss', 'xsd', 'wsdl'],
    extensions: [
      '.xml',
      '.adml',
      '.admx',
      '.ant',
      '.axml',
      '.builds',
      '.ccproj',
      '.ccxml',
      '.clixml',
      '.cproject',
      '.cscfg',
      '.csdef',
      '.csl',
      '.csproj',
      '.ct',
      '.depproj',
      '.dita',
      '.ditamap',
      '.ditaval',
      '.dll.config',
      '.dotsettings',
      '.filters',
      '.fsproj',
      '.fxml',
      '.glade',
      '.gml',
      '.gmx',
      '.grxml',
      '.iml',
      '.ivy',
      '.jelly',
      '.jsproj',
      '.kml',
      '.launch',
      '.mdpolicy',
      '.mjml',
      '.mm',
      '.mod',
      '.mxml',
      '.natvis',
      '.ncl',
      '.ndproj',
      '.nproj',
      '.nuspec',
      '.odd',
      '.osm',
      '.pkgproj',
      '.plist',
      '.pluginspec',
      '.proj',
      '.props',
      '.ps1xml',
      '.psc1',
      '.pt',
      '.rdf',
      '.resx',
      '.rss',
      '.sch',
      '.scxml',
      '.sfproj',
      '.shproj',
      '.srdf',
      '.storyboard',
      '.stTheme',
      '.sublime-snippet',
      '.targets',
      '.tmCommand',
      '.tml',
      '.tmLanguage',
      '.tmPreferences',
      '.tmSnippet',
      '.tmTheme',
      '.ts',
      '.tsx',
      '.ui',
      '.urdf',
      '.ux',
      '.vbproj',
      '.vcxproj',
      '.vsixmanifest',
      '.vssettings',
      '.vstemplate',
      '.vxml',
      '.wixproj',
      '.workflow',
      '.wsdl',
      '.wsf',
      '.wxi',
      '.wxl',
      '.wxs',
      '.x3d',
      '.xacro',
      '.xaml',
      '.xib',
      '.xlf',
      '.xliff',
      '.xmi',
      '.xml.dist',
      '.xproj',
      '.xsd',
      '.xspec',
      '.xul',
      '.zcml'
    ],
    filenames: [
      '.classpath',
      '.cproject',
      '.project',
      'App.config',
      'NuGet.config',
      'Settings.StyleCop',
      'Web.Debug.config',
      'Web.Release.config',
      'Web.config',
      'packages.config'
    ],
    language_id: 399
  },
  YAML: {
    type: 'data',
    tm_scope: 'source.yaml',
    aliases: ['yml'],
    extensions: [
      '.yml',
      '.mir',
      '.reek',
      '.rviz',
      '.sublime-syntax',
      '.syntax',
      '.yaml',
      '.yaml-tmlanguage',
      '.yml.mysql'
    ],
    filenames: ['.clang-format', '.clang-tidy', '.gemrc', 'glide.lock'],
    ace_mode: 'yaml',
    codemirror_mode: 'yaml',
    codemirror_mime_type: 'text/x-yaml',
    language_id: 407
  }
}
